controllers:
    resource: ../../src/Controller/
    type: annotation
    
# toutes les routes de toutes les classes de contrôleur 
# contenues dans le répertoire src/Controller/Admin
# seront préfixées par /admin
admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: /admin
